cc = g++
hardCodeCpp = bound.cpp constStr.cpp constChar.cpp constNum.cpp null.cpp sign.cpp
hardCodeObject = bound.o constStr.o constChar.o constNum.o null.o sign.o

constChar.o: $(PWD)/compile/lexical/hardCode/constChar.cpp
	$(cc) -c $(PWD)/compile/lexical/hardCode/constChar.cpp

constStr.o: $(PWD)/compile/lexical/hardCode/constStr.cpp
	$(cc) -c $(PWD)/compile/lexical/hardCode/constStr.cpp

constNum.o: $(PWD)/compile/lexical/hardCode/constNum.cpp
	$(cc) -c $(PWD)/compile/lexical/hardCode/constNum.cpp

null.o: $(PWD)/compile/lexical/hardCode/null.cpp
	$(cc) -c $(PWD)/compile/lexical/hardCode/null.cpp

sign.o: $(PWD)/compile/lexical/hardCode/sign.cpp
	$(cc) -c $(PWD)/compile/lexical/hardCode/sign.cpp

bound.o: $(PWD)/compile/lexical/hardCode/bound.cpp
	$(cc) -c $(PWD)/compile/lexical/hardCode/bound.cpp