#include "parser.h"
string* NonterminalMap;
string getNonterminalMap(int i) {
    return NonterminalMap[i];
}
void initNonterminalMap() {
    NonterminalMap = new string[60];
    NonterminalMap[PROGRAM] = "PROGRAM";
    NonterminalMap[SEGMENT] = "SEGMENT";
    NonterminalMap[TYPE] = "TYPE";
    NonterminalMap[DEF] = "DEF";
    NonterminalMap[DEFDATA] = "DEFDATA";
    NonterminalMap[VARRDEF] = "VARRDEF";
    NonterminalMap[INIT] = "INIT";
    NonterminalMap[EXPR] = "EXPR";
    NonterminalMap[DEFLIST] = "DEFLIST";
    NonterminalMap[FUN] = "FUN";
    NonterminalMap[PARA] = "PARA";
    NonterminalMap[BLOCK] = "BLOCK";
    NonterminalMap[FUNTAIL] = "FUNTAIL";
    NonterminalMap[IDTAIL] = "IDTAIL";
    NonterminalMap[PARADATA] = "PARADATA";
    NonterminalMap[PARADATATAIL] = "PARADATATAIL";
    NonterminalMap[PARALIST] = "PARALIST";
    NonterminalMap[SUBPROGRAM] = "SUBPROGRAM";
    NonterminalMap[LOCALDEF] = "LOCALDEF";
    NonterminalMap[STATEMENT] = "STATEMENT";
    NonterminalMap[ASSEXPR] = "ASSEXPR";
    NonterminalMap[ASSTAIL] = "ASSTAIL";
    NonterminalMap[OREXPR] = "OREXPR";
    NonterminalMap[ORTAIL] = "ORTAIL";
    NonterminalMap[ANDEXPR] = "ANDEXPR";
    NonterminalMap[ANDTAIL] = "ANDTAIL";
    NonterminalMap[CMPEXPR] = "CMPEXPR";
    NonterminalMap[CMPTAIL] = "CMPTAIL";
    NonterminalMap[CMPS] = "CMPS";
    NonterminalMap[ALOEXPR] = "ALOEXPR";
    NonterminalMap[ALOTAIL] = "ALOTAIL";
    NonterminalMap[ADDS] = "ADDS";
    NonterminalMap[MULS] = "MULS";
    NonterminalMap[ITEM] = "ITEM";
    NonterminalMap[FACTOR] = "FACTOR";
    NonterminalMap[ITEMTAIL] = "ITEMTAIL";
    NonterminalMap[LOP] = "LOP";
    NonterminalMap[VAL] = "VAL";
    NonterminalMap[ELEM] = "ELEM";
    NonterminalMap[ROP] = "ROP";
    NonterminalMap[IDEXPR] = "IDEXPR";
    NonterminalMap[LITERAL] = "LITERAL";
    NonterminalMap[REALARG] = "REALARG";
    NonterminalMap[ARGLIST] = "ARGLIST";
    NonterminalMap[ARG] = "ARG";
    NonterminalMap[ALTEXPR] = "ALTEXPR";
    NonterminalMap[WHILESTAT] = "WHILESTAT";
    NonterminalMap[FORSTAT] = "FORSTAT";
    NonterminalMap[DOWHILESTAT] = "DOWHILESTAT";
    NonterminalMap[IFSTAT] = "IFSTAT";
    NonterminalMap[SWITCHSTAT] = "SWITCHSTAT";
    NonterminalMap[FORINIT] = "FORINIT";
    NonterminalMap[ELSESTAT] = "ELSESTAT";
    NonterminalMap[CASESTAT] = "CASESTAT";
    NonterminalMap[CASELABEL] = "CASELABEL";
    NonterminalMap[ROOT] = "ROOT";
}